org: udithshalinda3
app: expense-service
service: expense-service

custom:
  stages:
    - dev
    - staging
    - prod

provider:
  name: aws
  stage: ${opt:stage,'dev'}
  runtime: nodejs20.x
  region: us-east-1

  environment:
    PORT: 3000
    DB_URL: 'mongodb+srv://udithshalinda2:2RLJEE2HNKABE97G@cluster0.01mvz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  app:
    handler: ./src/index.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

build:
  esbuild: false
